### ISSUE TITLE
Question: How about JS from npm modules?

### ISSUE THREAD

**Issue by pogo19** [eddyson-de/tapestry-webjars#2]
Hi!

First, really thanks for your tapestry-webjars and tapestry-react projects.

I am using tapestry-react and tapestry-webjars to have react and want it to use react-gmaps. But unfortunately when using react-gmaps I get `ReferenceError: exports is not defined`.

From what I've found it means that browser doesn't support CommonJS modules. I thought that tapestry should get that resolved with its new T5.4 JavaScript framework rewrite.

Can you help me in any way? For me it looks like that JS file from webjar is being sent to browser without standard Tapestry processing. Am I right? What can I do about it?

Thanks a lot!

Jan

**Comment by jochenberger** [comment]
Yes, CommonJS modules need some special treatment. In one of my projects,I created a `CommonJSAMDWrapper` (similar to Tapestry's `AMDWrapper`), that transforms the module as explained on http://requirejs.org/docs/api.html#cjsmodule. I could add that to `tapestry-webjars`.

**Comment by pogo19** [comment]
Thanks for answer. If you could add that to tapestry-webjars, it would be great :)

**Comment by jochenberger** [comment]
`CommonJSAMDWrapper` is available in 0.9.5, see https://github.com/eddyson-de/tapestry-webjars#working-with-commonjs-modules.
